routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace' => 'Member','middleware' => 'auth'], function () {
    // networks routes
    Route::prefix('networks')->group(function () {
        // Registration Routes...
        Route::get('register', 'UserController@create')->name('register');
        Route::post('registerpost', 'UserController@store')->name('register.store');

        Route::get('genealogy/{top_id?}', 'MemberstructureController@genealogy')->name('genealogy');
        Route::get('placement-list/{parent_id}/{position}', 'MemberstructureController@getPlacementList')->name('placement.list');
        Route::post('placement', 'MemberstructureController@placement')->name('placement');
        Route::get('all', 'MemberstructureController@all')->name('networks.all');
        Route::get('all-data', 'MemberstructureController@allData')->name('networks.all.data');
        Route::get('sponsor', 'UserController@sponsor')->name('networks.sponsor');
        Route::get('sponsor-data', 'UserController@sponsorData')->name('networks.sponsor.data');
    });

    // bonus routes
    Route::prefix('bonus')->group(function () {
        Route::get('summary', 'BonusController@summary')->name('bonus.summary');
        Route::get('summary-data', 'BonusController@summaryData')->name('bonus.summary.data');
        Route::get('sponsor', 'BonusController@sponsor')->name('bonus.sponsor');
        Route::get('sponsor-data', 'BonusController@sponsorData')->name('bonus.sponsor.data');
        Route::get('pairing', 'BonusController@pairing')->name('bonus.pairing');
        Route::get('pairing-data', 'BonusController@pairingData')->name('bonus.pairing.data');
        Route::get('pairing-level', 'BonusController@pairingLevel')->name('bonus.pairing-level');
        Route::get('pairing-level-data', 'BonusController@pairingLevelData')->name('bonus.pairing-level.data');
    });

    // reward routes
    Route::prefix('reward')->group(function () {
        Route::get('my-achievement', 'MemberRewardController@index')->name('reward.achievement');
        Route::get('my-savings/{reward_setting}', 'MemberRewardSavingController@index')->name('reward.saving');
        Route::get('my-savings-data/{reward_setting}', 'MemberRewardSavingController@getSavingData')->name('reward.saving.data');
        Route::get('reward-claim/{member_reward_id}', 'MemberRewardController@claim')->name('reward.claim');
    });

    // withdrawal routes
    Route::prefix('withdrawal')->group(function () {
        Route::get('withdrawal', 'WithdrawalController@index')->name('withdrawal.index');
        Route::get('withdrawal-data', 'WithdrawalController@getWithdrawalData')->name('withdrawal.data');
    });

    //user My Account routes
    Route::prefix('my-account')->group(function () {
        Route::get('/', 'AccountController@profile')->name('my.account');
        Route::get('address', 'AccountController@address')->name('my.account.address');
        Route::get('id', 'AccountController@identity')->name('my.account.id');
        Route::put('/{user}', 'AccountController@store')->name('my.account.store');
        Route::put('bank/{bank}', 'AccountController@updateBank')->name('my.account.bank.update');
        Route::get('bank/{bank}', 'AccountController@togleBankStatus')->name('my.account.bank.status');
        Route::get('bank', 'AccountController@bank')->name('my.account.bank');
        Route::post('bank', 'AccountController@storeBank')->name('my.account.bank.store');
        Route::get('change-password', 'AccountController@changePassword')->name('my.account.changepw');
    });

    // user PIN
    Route::resources([
        'user-pin' => 'UserPinController',
    ]);
    Route::get('pin-data', 'UserPinController@getUserPinData')->name('user.pin.data');
    Route::get('pin-available', 'UserPinController@available')->name('user.pin.available');
    Route::get('pin-available-data', 'UserPinController@getAvailableData')->name('user.pin.available.data');
    Route::get('pin-used', 'UserPinController@used')->name('user.pin.used');
    Route::get('pin-used-data', 'UserPinController@getUsedData')->name('user.pin.used.data');
    Route::get('pin-sold', 'UserPinController@sold')->name('user.pin.sold');
    Route::get('pin-sold-data', 'UserPinController@getSoldData')->name('user.pin.sold.data');
    Route::get('pin-transferred', 'UserPinController@transferred')->name('user.pin.transferred');
    Route::get('pin-transferred-data', 'UserPinController@getTransferredData')->name('user.pin.transferred.data');

    // user PIN Transaction
    Route::resources([
        'transaction-pin' => 'PinTransactionController',
    ]);

    Route::prefix('transactionpin')->group(function () {
        Route::get('data', 'PinTransactionController@getTransactionHistoryData')->name('transaction.pin.data');
        Route::post('stockist-based-on-plan', 'PinTransactionController@getStockistBasedOnPlan')->name('transaction.get.stockist');
        Route::get('running', 'PinTransactionController@runningTransaction')->name('transaction.pin.running');
        Route::get('running-data', 'PinTransactionController@getRunningTransactionData')->name('transaction.running.pin.data');
        Route::get('invoice/{pin_transaction}', 'PinTransactionController@invoice')->name('transaction.pin.invoice');
        Route::get('upload/{pin_transaction}', 'PinTransactionController@upload')->name('transaction.pin.upload');
        Route::post('upload/{pin_transaction}', 'PinTransactionController@doUpload')->name('transaction.pin.doupload');
        Route::get('image/{pin_transaction}', 'PinTransactionController@image')->name('transaction.pin.image');
        Route::post('reject', 'PinTransactionController@reject')->name('transaction.pin.reject');
    });

    // user Request Stockist
    Route::prefix('stockist')->group(function () {
        Route::get('request', 'RequestStockistController@index')->name('stockist.request');
        Route::post('post-request', 'RequestStockistController@postRequest')->name('stockist.request.post');
    });

    Route::post('get-regency', 'AccountController@getRegency')->name('get.regency');
    Route::post('get-district', 'AccountController@getDistrict')->name('get.district');
    Route::post('get-village', 'AccountController@getVillage')->name('get.village');
});

Route::middleware(['auth'])->group(function () {
    //** ADMIN MENU GROUP ROUTES
    Route::group(['prefix' => 'admin', 'middleware' => ['role:super-administrator|administrators']], function () {

        //PIN routes
        Route::resources([
            'pin' => 'Admin\PinController',
        ]);
        Route::get('pin-data', 'Admin\PinController@getPinData')->name('pin.data');
        Route::get('pin-history', 'Admin\PinController@history')->name('pin.history');
        Route::get('pin-history-data', 'Admin\PinController@getPinHistoryData')->name('pin.history.data');
        Route::post('pin-reject', 'Admin\PinController@reject')->name('pin.reject');

        //Withdrawal route
        Route::get('withdrawal', 'Admin\WithdrawalController@index')->name('admin.withdrawal.index');
        Route::get('withdrawal-data', 'Admin\WithdrawalController@getWithdrawalData')->name('admin.withdrawal.index.data');
        Route::get('withdrawal-history', 'Admin\WithdrawalController@history')->name('admin.withdrawal.history');
        Route::get('withdrawal-history-data', 'Admin\WithdrawalController@getWithdrawalHistoryData')->name('admin.withdrawal.history.data');
        Route::put('withdrawal-transfer', 'Admin\WithdrawalController@transfer')->name('admin.withdrawal.transfer');

        //Reward route
        Route::get('reward', 'Admin\MemberRewardController@index')->name('admin.member-reward.index');
        Route::get('reward-data', 'Admin\MemberRewardController@getRewardData')->name('admin.member-reward.index.data');
        Route::get('reward-history', 'Admin\MemberRewardController@history')->name('admin.member-reward.history');
        Route::get('reward-history-data', 'Admin\MemberRewardController@getRewardHistoryData')->name('admin.member-reward.history.data');
        Route::put('reward-process', 'Admin\MemberRewardController@process')->name('admin.member-reward.process');

        //Request Stockist route
        Route::get('request-stockist', 'Admin\RequestStockistController@index')->name('admin.request-stockist.index');
        Route::get('request-stockist-data', 'Admin\RequestStockistController@getRequestStockistData')->name('admin.request-stockist.index.data');
        Route::get('request-stockist-history', 'Admin\RequestStockistController@history')->name('admin.request-stockist.history');
        Route::get('request-stockist-history-data', 'Admin\RequestStockistController@getRequestStockistHistoryData')->name('admin.request-stockist.history.data');
        Route::put('request-stockist-process', 'Admin\RequestStockistController@process')->name('admin.request-stockist.process');
        Route::get('stockist', 'Admin\RequestStockistController@stockistIndex')->name('admin.stockist.index');

        // Plan Setting routes
        Route::resources([
            'plan-settings' => 'Admin\PlanSettingController',
        ]);
        Route::resources([
            'plan-price' => 'Admin\PlanPriceHistoryController',
        ]);
        Route::get('plan-settings-data', 'Admin\PlanSettingController@getPlanSettingData')->name('plan.setting.data');

        // Bonus Setting routes
        Route::resources([

app/Http/Controllers/Admin/PinController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Repositories\PinTransactionInterface;
use App\Tools\PinTransactionsTool;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;

class PinController extends Controller
{
    use PinTransactionsTool;

    private $pin_transaction;

    public function __construct(
        PinTransactionInterface $pin_transaction
    ) {
        $this->pin_transaction = $pin_transaction;
    }

    public function index()
    {
        return view(
            'admin.pin.transaction-index'
        );
    }

    public function getPinData()
    {
        $pin_transaction = $this->pin_transaction->getCompanyPinTransaction();

        return DataTables::of($pin_transaction)
             ->addColumn('transaction', function ($pin_transaction) {
                 return $this->strTransactionCompany($pin_transaction);
             })
             ->addColumn('total_amount', function ($pin_transaction) {
                 return 'Rp '. number_format($pin_transaction->price + $pin_transaction->unique_digit, 0, ',', '.');
             })
             ->addColumn('action', function ($pin_transaction) {
                 return $this->actionButton($pin_transaction);
             })
             ->addColumn('status_date', function ($pin_transaction) {
                 return $this->status_date($pin_transaction);
             })
             ->editColumn('status', function ($pin_transaction) {
                 return $this->str_status($pin_transaction);
             })
             ->editColumn('transaction_code', function ($pin_transaction) {
                 return $this->transaction_code($pin_transaction);
             })
             ->rawColumns(['action', 'transaction', 'total_amount', 'transaction_code', 'status_date', 'status'])
             ->make(true);
    }

    public function history()
    {
        return view(
            'admin.pin.transaction-history'
        );
    }

    public function getPinHistoryData()
    {
        $pin_transaction = $this->pin_transaction->getCompanyPinHistory();

        return DataTables::of($pin_transaction)
            ->addColumn('transaction', function ($pin_transaction) {
                return $this->strTransactionCompany($pin_transaction);
            })
            ->addColumn('total_amount', function ($pin_transaction) {
                return 'Rp '. number_format($pin_transaction->price + $pin_transaction->unique_digit, 0, ',', '.');
            })
            ->addColumn('status_date', function ($pin_transaction) {
                return $this->status_date($pin_transaction);
            })
            ->editColumn('status', function ($pin_transaction) {
                return $this->str_status($pin_transaction);
            })
            ->editColumn('transaction_code', function ($pin_transaction) {
                return $this->transaction_code($pin_transaction);
            })
            ->rawColumns(['action', 'transaction', 'total_amount', 'transaction_code', 'status_date', 'status'])
            ->make(true);
    }

    public function reject(Request $request)
    {
        $transaction = $this->pin_transaction->find($request['id']);

        if ($transaction->from != 11) {
            return redirect(
                route(
                    'pin.index'
                )
            )->with(
                'error',
                'Terdeteksi manipulasi data transaksi!!!'
            );
        }

        try {
            $transaction->status = 'rejected';
            $transaction->status_note = $request['status_note'];
            $transaction->rejected_at = Carbon::now('Asia/Jakarta');
            $transaction->save();
        } catch (\Exception $e) {
            return redirect(
                route(
                    'pin.index'
                )
            )->with(
                'error',
                'Penolakan transaksi PIN Gagal!'
            );
        }

        return redirect(
            route(
                'pin.index'
            )
        )->with(
            'success',
            'Transaksi '. $transaction->transaction_code .' berhasil ditolak!'
        );
    }
}

app/Http/Controllers/Member/BonusController.php
<?php

namespace App\Http\Controllers\Member;

use App\Models\Bonus;
use App\Repositories\BonusInterface;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class BonusController extends Controller
{
	private $bonus;

	public function __construct (BonusInterface $bonus) {
		$this->bonus = $bonus;
	}

	public function summary()
	{
		$sponsor = system_settings()->bonus_sponsor;
		$pairing = system_settings()->bonus_pairing;
		$level = system_settings()->bonus_level;
		$pairing_level = system_settings()->bonus_pairing_level;

		$i = 0;
		$i = ($sponsor) ? ($i + 1) : $i;
		$i = ($pairing) ? ($i + 1) : $i;
		$i = ($level) ? ($i + 1) : $i;
		$i = ($pairing_level) ? ($i + 1) : $i;

		$sponsor_total = $this->bonus->getTotalBonusSponsor();
		$pairing_total = $this->bonus->getTotalBonusPairing();
		$pairing_level_total = $this->bonus->getTotalBonusPairingLevel();

		return view(
			'member.bonus.summary',
			compact(
				'i',
				'sponsor_total',
				'pairing_total',
				'pairing_level_total'
			)
		);
	}

	public function summaryData()
	{
		$data = $this->bonus->getMyBonus();

		return DataTables::of($data)
			->addColumn('bonus_sponsor', function ($data) {
				return number_format($data->bonus_sponsor,0,',','.');
			})
			->addColumn('bonus_pairing', function ($data) {
				return number_format($data->bonus_pairing,0,',','.');
			})
			->addColumn('bonus_pairing_level', function ($data) {
				return number_format($data->bonus_pairing_level,0,',','.');
			})
			->addColumn('bonus_level', function ($data) {
				return number_format($data->bonus_level,0,',','.');
			})
			->addColumn('bonus_date', function ($data) {
				return str_replace(' +07:00','',to_utz($data->created_at));
			})
			->addColumn('from_user', function ($data) {
				return $data->from->name;
			})
			->rawColumns(['from_user'])
			->make(true);
	}

	public function sponsor()
	{
		return view(
			'member.bonus.sponsor'
		);
	}

	public function sponsorData()
	{
		$data = $this->bonus->getMySponsorBonus();

		return DataTables::of($data)
			->addColumn('bonus_amount', function ($data) {
				return number_format($data->bonus_sponsor,0,',','.');
			})
			->addColumn('bonus_date', function ($data) {
				return str_replace(' +07:00','',to_utz($data->created_at));
			})
			->addColumn('from_user', function ($data) {
				return $data->from->name .' ('. $data->from->username .')';
			})
			->rawColumns(['from_user'])
			->make(true);
	}

	public function pairing()
	{
		return view(
			'member.bonus.pairing'
		);
	}

	public function pairingData()
	{
		$data = $this->bonus->getMyPairingBonus();

		return DataTables::of($data)
			->addColumn('bonus_amount', function ($data) {
				return number_format($data->bonus_pairing,0,',','.');
			})
			->addColumn('bonus_date', function ($data) {
				return str_replace(' +07:00','',to_utz($data->created_at));
			})
			->addColumn('from_user', function ($data) {
				return $data->from->name .' ('. $data->from->username .')';
			})
			->rawColumns(['from_user'])
			->make(true);
	}

	public function pairingLevel()
	{
		return view(
			'member.bonus.pairing-level'
		);
	}

	public function pairingLevelData()
	{
		$data = $this->bonus->getMyPairingLevelBonus();

		return DataTables::of($data)
			->addColumn('bonus_amount', function ($data) {
				return number_format($data->bonus_pairing_level,0,',','.');
			})
			->addColumn('bonus_date', function ($data) {
				return str_replace(' +07:00','',to_utz($data->created_at));
			})
			->addColumn('from_user', function ($data) {
				return $data->from->name .' ('. $data->from->username .')';
			})
			->rawColumns(['from_user'])
			->make(true);
	}
}

resources/views/member/pin/create.blade.php
@extends('layouts.member')

@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
@endsection

@section('content')
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">Beli Pin</h4>
        </div>
        <div class="card-body">
          <form method="post" class="form-horizontal" action="{{ route('transaction-pin.store') }}">
            @csrf
            <input type="hidden" name="type" value="buy">
            <div class="row">
              <div class="col-md-3">
                <label class="bmd-label-floating">Beli PIN dari</label>
              </div>
              <div class="col-md-6">
                <div class="form-group bmd-form-group {{$errors->has('stockist_id') ? 'danger' : ''}}">
                  @if( $plans->count() > 1 )
                  <select name="stockist_id" class="form-control select2" data-toggle="select2">
                      <option value="" selected disabled>--- Pilih Stockist ---</option>
                      @foreach($stockist_list as $key => $plan)
                          @if(old('stockist_id')==$key)
                              <option value="{{ $key }}" selected>{{ $plan }}</option>
                          @else
                              <option value="{{ $key }}">{{ $plan }}</option>
                          @endif
                      @endforeach
                  </select>
                  @else
                  <select name="stockist_id" class="form-control select2" data-toggle="select2">
                      <option value="" selected disabled>--- Pilih Stockist ---</option>
                      @foreach($stockist_list as $key => $plan)
                          @if(old('stockist_id')==$key)
                              <option value="{{ $key }}" selected>{{ $plan }}</option>
                          @else
                              <option value="{{ $key }}">{{ $plan }}</option>
                          @endif
                      @endforeach
                  </select>
                  @endif
                  @if($errors->has('stockist_id'))
                      <label id="exampleEmails-error" class="error" for="exampleEmails">{{ $errors->first('stockist_id') }}</label>
                  @endif

                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3">
                <label class="bmd-label-floating">Jumlah Pin</label>
              </div>
              <div class="col-md-6">
                <div class="form-group bmd-form-group {{$errors->has('amount') ? 'danger' : ''}}">
                  <input type="number" class="form-control" name="amount" value="{{ old('amount') }}">
                  @if($errors->has('amount'))
                      <label id="exampleEmails-error" class="error" for="exampleEmails">{{ $errors->first('amount') }}</label>
                  @endif

                </div>
              </div>
            </div>
              <div class="col-md-6">
                @if( $plans->count() > 1 )
                  <div class="form-group bmd-form-group {{$errors->has('plan_id') ? 'danger' : ''}}">
                    <select name="plan_id" class="form-control select2" data-toggle="select2">
                        <option value="" selected disabled>--- Pilih Paket ---</option>
                        @foreach($plans as $key => $plan)
                            @if(old('plan_id')==$key)
                                <option value="{{ $key }}" selected>{{ $plan }}</option>
                            @else
                                <option value="{{ $key }}">{{ $plan }}</option>
                            @endif
                        @endforeach
                    </select>
                    @if($errors->has('plan_id'))
                        <label id="exampleEmails-error" class="error" for="exampleEmails">{{ $errors->first('plan_id') }}</label>
                    @endif
                  </div>
                @else
                  @foreach($plans as $key => $plan)
                      <input type="hidden" name="plan_id" value="{{ $key }}">
                  @endforeach
                @endif
              </div>
              <div class="col-md-9">
                <button type="submit" class="btn btn-primary pull-right">Order<div class="ripple-container"></div></button>
                <a class="btn btn-secondary pull-right" href="{{ route('user-pin.index') }}">Cancel</a>
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
@endsection

@section('page_script')
<script type="text/javascript">
$(document).ready(function() {
  $('.select2').select2();
});
</script>
    @if( $plans->count() > 1 )
        <script>
            $('#plan_id').on('select2:select', function (e) {
                var data = e.params.data;
                //console.log(data);

                $('#stockist_id').empty();
                $.ajax({
                    method: "POST",
                    url: '{{ route('transaction.get.stockist') }}',
                    data: {
                        "_token": "{{ csrf_token() }}",
                        "id": data.id
                    },
                    success: data => {
                        //console.log(data);
                        for (var opt in data) {
                            $('#stockist_id').append('<option value="'+ opt +'">'+ data[opt] +'</option>');
                        }
                    }
                })
            });
        </script>
    @endif

    <script>
        $(function(){
            'use strict'

            $('.form-layout .form-control').on('focusin', function(){
                $(this).closest('.form-group').addClass('form-group-active');
            });

            $('.form-layout .form-control').on('focusout', function(){
                $(this).closest('.form-group').removeClass('form-group-active');
            });

            $('.select2').on('select2:opening', function (e) {
                $(this).closest('.form-group').addClass('form-group-active');
            });

            $('.select2').on('select2:closing', function (e) {
                $(this).closest('.form-group').removeClass('form-group-active');
            });

        });
    </script>

    @if (session('success'))
        <div id="modalsukses" class="modal fade">
            <div class="modal-dialog" role="document">
                <div class="modal-content tx-size-sm">
                    <div class="modal-body tx-center pd-y-20 pd-x-20">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <i class="icon ion-ios-checkmark-outline tx-100 tx-success lh-1 mg-t-20 d-inline-block"></i>
                        <h4 class="tx-success tx-semibold mg-b-20">Sukses!</h4>
                        <p class="mg-b-20 mg-x-20">{{ session('success') }}</p>
                        <button type="button" class="btn btn-success tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium mg-b-20" data-dismiss="modal" aria-label="Close"> OK</button>
                    </div><!-- modal-body -->
                </div><!-- modal-content -->
            </div><!-- modal-dialog -->
        </div><!-- modal -->
        <script>
            $('#modalsukses').modal('show');
        </script>
    @endif

    @if (session('error'))
        <div id="modalerrordelete" class="modal fade">
            <div class="modal-dialog" role="document">
                <div class="modal-content tx-size-sm">
                    <div class="modal-body tx-center pd-y-20 pd-x-20">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <i class="icon ion-ios-close-outline tx-100 tx-danger lh-1 mg-t-20 d-inline-block"></i>
                        <h4 class="tx-danger tx-semibold mg-b-20">Error!</h4>
                        <p class="mg-b-20 mg-x-20">{{ session('error') }}</p>
                        <button type="button" class="btn btn-danger tx-11 tx-uppercase pd-y-12 pd-x-25 tx-mont tx-medium mg-b-20" data-dismiss="modal" aria-label="Close"> OK</button>
                    </div><!-- modal-body -->
                </div><!-- modal-content -->
            </div><!-- modal-dialog -->
        </div><!-- modal -->
        <script>
            $('#modalerrordelete').modal('show');
        </script>
    @endif

@endsection

resources/views/member/pin/sold.blade.php
@extends('layouts.member')

@section('styles')
    <link href="{{ asset('admin/lib/select2/css/select2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/lib/datatables/jquery.dataTables.css') }}" rel="stylesheet">
@endsection

@section('content')
    <div class="br-pageheader pd-y-15 pd-l-20">
    </div><!-- br-pageheader -->
    <div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
        <div class="pull-left">
            <h4 class="tx-gray-800 mg-b-5">PIN</h4>
        </div>
    </div>

    <div class="br-pagebody mg-t-35 pd-x-20 pd-sm-x-30">
        <div class="row no-gutters widget-1 shadow-base">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h6 class="card-title">PIN Terjual</h6>
                        <a href=""><i class="icon ion-android-more-horizontal"></i></a>
                    </div><!-- card-header -->
                    <div class="card-body">
                        <span id="spark1"><canvas style="display: inline-block; width: 89px; height: 30px; vertical-align: top;" width="89" height="30"></canvas></span>
                        <span>{{ count_pin_sold(auth()->id()) }}</span>
                    </div><!-- card-body -->
                    <div class="card-footer">
                        <div>
                            <a href="{{ route('user-pin.index') }}">
                                <span class="tx-11">Tersedia</span>
                                <h6 class="tx-inverse">{{ count_pin_available(auth()->id()) }}</h6>
                            </a>
                        </div>
                        <div>
                            <a href="{{ route('user.pin.used') }}">
                                <span class="tx-11">Terpakai</span>
                                <h6 class="tx-inverse">{{ count_pin_used(auth()->id()) }}</h6>
                            </a>
                        </div>
                    </div><!-- card-footer -->
                </div>
            </div>
        </div>
    </div>
    <div class="br-pagebody mg-t-15">
        <div class="br-section-wrapper pd-20">
            <div class="table-wrapper">
                <table id="plan-setting-data" class="table dt-responsive nowrap">
                    <thead>
                    <tr>
                        <th class="wd-25p">Kode Pin</th>
                        <th class="wd-30p">Status</th>
                        <th></th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('admin/lib/select2/js/select2.min.js') }}"></script>
    <script src="{{ asset('admin/lib/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('admin/lib/datatables-responsive/dataTables.responsive.js') }}"></script>
@endsection

@section('page_script')
    <script>
        $(function(){
            'use strict';

            $('#plan-setting-data').DataTable({
                responsive: false,
                language: {
                    searchPlaceholder: 'Cari...',
                    sSearch: '',
                    lengthMenu: '_MENU_ data/halaman',
                    zeroRecords: ' Tidak ada data yang dapat ditampilkan.',
                    info: 'Menampilkan halaman _PAGE_ dari _PAGES_ (Total Data : _MAX_)',
                    infoEmpty: '',
                    infoFiltered: "(disaring dari total _MAX_ data)"
                },
                processing: true,
                serverSide: true,
                ajax: '{{ route('user.pin.sold.data') }}',
                columns: [
                    {data: 'pin_code', name: 'pin_code'},
                    {data: 'status', name: 'status',
                        render: function(data, type, row, meta){
                            if(type === 'display'){
                                if(data == 0){
                                    data = '<span class="text-success">tersedia</span>';
                                } else if(data == 1){
                                    data = '<span class="text-warning">terjual</span>';
                                } else if(data == 2){
                                    data = '<span class="text-purple">ditransfer</span>';
                                } else if(data == 3){
                                    data = '<span class="text-info">digunakan</span>';
                                }
                            }
                            return data;
                        }
                    },
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });

            $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

        });
    </script>
@endsection