routes/web.php
        Route::put('/{user}', 'AccountController@store')->name('my.account.store');
        Route::put('bank/{bank}', 'AccountController@updateBank')->name('my.account.bank.update');
        Route::get('bank/{bank}', 'AccountController@togleBankStatus')->name('my.account.bank.status');
        Route::get('bank', 'AccountController@bank')->name('my.account.bank');
        Route::post('bank', 'AccountController@storeBank')->name('my.account.bank.store');
        Route::get('change-password', 'AccountController@changePassword')->name('my.account.changepw');
    });

    // user PIN
    Route::resources([
        'user-pin' => 'UserPinController',
    ]);
    Route::get('pin-data', 'UserPinController@getUserPinData')->name('user.pin.data');
    Route::get('pin-available', 'UserPinController@available')->name('user.pin.available');
    Route::get('pin-available-data', 'UserPinController@getAvailableData')->name('user.pin.available.data');
    Route::get('pin-used', 'UserPinController@used')->name('user.pin.used');
    Route::get('pin-used-data', 'UserPinController@getUsedData')->name('user.pin.used.data');
    Route::get('pin-sold', 'UserPinController@sold')->name('user.pin.sold');
    Route::get('pin-sold-data', 'UserPinController@getSoldData')->name('user.pin.sold.data');
    Route::get('pin-transferred', 'UserPinController@transferred')->name('user.pin.transferred');
    Route::get('pin-transferred-data', 'UserPinController@getTransferredData')->name('user.pin.transferred.data');

    // user PIN Transaction
    Route::resources([
        'transaction-pin' => 'PinTransactionController',
    ]);

    Route::prefix('transactionpin')->group(function () {
        Route::get('data', 'PinTransactionController@getTransactionHistoryData')->name('transaction.pin.data');
        Route::post('stockist-based-on-plan', 'PinTransactionController@getStockistBasedOnPlan')->name('transaction.get.stockist');
        Route::get('running', 'PinTransactionController@runningTransaction')->name('transaction.pin.running');
        Route::get('running-data', 'PinTransactionController@getRunningTransactionData')->name('transaction.running.pin.data');
        Route::get('invoice/{pin_transaction}', 'PinTransactionController@invoice')->name('transaction.pin.invoice');
        Route::get('upload/{pin_transaction}', 'PinTransactionController@upload')->name('transaction.pin.upload');
        Route::post('upload/{pin_transaction}', 'PinTransactionController@doUpload')->name('transaction.pin.doupload');
        Route::get('image/{pin_transaction}', 'PinTransactionController@image')->name('transaction.pin.image');
        Route::post('reject', 'PinTransactionController@reject')->name('transaction.pin.reject');
    });

    // user Request Stockist
    Route::prefix('stockist')->group(function () {
        Route::get('request', 'RequestStockistController@index')->name('stockist.request');
        Route::post('post-request', 'RequestStockistController@postRequest')->name('stockist.request.post');
    });

    Route::post('get-regency', 'AccountController@getRegency')->name('get.regency');
    Route::post('get-district', 'AccountController@getDistrict')->name('get.district');
    Route::post('get-village', 'AccountController@getVillage')->name('get.village');
});

Route::middleware(['auth'])->group(function () {
    //** ADMIN MENU GROUP ROUTES
    Route::group(['prefix' => 'admin', 'middleware' => ['role:super-administrator|administrators']], function () {

        //PIN routes
        Route::resources([
            'pin' => 'Admin\PinController',
        ]);
        Route::get('pin-data', 'Admin\PinController@getPinData')->name('pin.data');
        Route::get('pin-history', 'Admin\PinController@history')->name('pin.history');
        Route::get('pin-history-data', 'Admin\PinController@getPinHistoryData')->name('pin.history.data');
        Route::post('pin-reject', 'Admin\PinController@reject')->name('pin.reject');

        //Withdrawal route
        Route::get('withdrawal', 'Admin\WithdrawalController@index')->name('admin.withdrawal.index');
        Route::get('withdrawal-data', 'Admin\WithdrawalController@getWithdrawalData')->name('admin.withdrawal.index.data');
        Route::get('withdrawal-history', 'Admin\WithdrawalController@history')->name('admin.withdrawal.history');
        Route::get('withdrawal-history-data', 'Admin\WithdrawalController@getWithdrawalHistoryData')->name('admin.withdrawal.history.data');
        Route::put('withdrawal-transfer', 'Admin\WithdrawalController@transfer')->name('admin.withdrawal.transfer');

        //Reward route
        Route::get('reward', 'Admin\MemberRewardController@index')->name('admin.member-reward.index');
        Route::get('reward-data', 'Admin\MemberRewardController@getRewardData')->name('admin.member-reward.index.data');
        Route::get('reward-history', 'Admin\MemberRewardController@history')->name('admin.member-reward.history');
        Route::get('reward-history-data', 'Admin\MemberRewardController@getRewardHistoryData')->name('admin.member-reward.history.data');
        Route::put('reward-process', 'Admin\MemberRewardController@process')->name('admin.member-reward.process');

        //Request Stockist route
        Route::get('request-stockist', 'Admin\RequestStockistController@index')->name('admin.request-stockist.index');
        Route::get('request-stockist-data', 'Admin\RequestStockistController@getRequestStockistData')->name('admin.request-stockist.index.data');
        Route::get('request-stockist-history', 'Admin\RequestStockistController@history')->name('admin.request-stockist.history');
        Route::get('request-stockist-history-data', 'Admin\RequestStockistController@getRequestStockistHistoryData')->name('admin.request-stockist.history.data');
        Route::put('request-stockist-process', 'Admin\RequestStockistController@process')->name('admin.request-stockist.process');
        Route::get('stockist', 'Admin\RequestStockistController@stockistIndex')->name('admin.stockist.index');

        // Plan Setting routes
        Route::resources([
            'plan-settings' => 'Admin\PlanSettingController',
        ]);
        Route::resources([
            'plan-price' => 'Admin\PlanPriceHistoryController',
        ]);
        Route::get('plan-settings-data', 'Admin\PlanSettingController@getPlanSettingData')->name('plan.setting.data');

        // Bonus Setting routes
        Route::resources([
            'bonus-settings' => 'Admin\BonusSettingController',
        ]);
        Route::get('bonus-settings-data', 'Admin\BonusSettingController@getBonusSettingData')->name('bonus.setting.data');

        // Reward Setting routes
        Route::resources([
            'reward-settings' => 'Admin\RewardSettingController',
        ]);
        Route::get('reward-settings-data', 'Admin\RewardSettingController@getRewardSettingData')->name('reward.setting.data');

        // Rewards routes
        Route::resources([
            'rewards' => 'Admin\RewardController',
        ]);
        Route::get('rewards-data', 'Admin\RewardController@getRewardsData')->name('rewards.data');

        // WithdrawalService Setting routes
        Route::resources([
            'withdrawal-settings' => 'Admin\WithdrawalSettingController',
        ]);
        Route::get('withdrawal-settings-data', 'Admin\WithdrawalSettingController@getWithdrawalSettingData')->name('withdrawal.setting.data');

        // Pin Setting routes
        Route::prefix('pin-settings')->group(function () {
            Route::get('/', 'Admin\PinSettingController@index')->name('pin-settings.index');
            Route::get('data', 'Admin\PinSettingController@getPinSettingData')->name('pin.setting.data');
            Route::get('generate', 'Admin\PinSettingController@generatePinForm')->name('pin.generate');
            Route::post('generate', 'Admin\PinSettingController@generatePinPost')->name('pin.generate.post');
        });

        // Stockist Setting routes
        Route::resources([
            'stockist-settings' => 'Admin\StockistSettingController',
        ]);
        Route::get('stockist-settings-data', 'Admin\StockistSettingController@getStockistSettingData')->name('stockist.setting.data');

        // Company Bank routes
        Route::resources([
            'company-bank' => 'Admin\CompanyBankController',
        ]);
        Route::get('company-bank-data', 'Admin\CompanyBankController@getCompanyBankData')->name('company.bank.data');

        //** SUPER-ADMIN MENU GROUP ROUTES
        Route::group(['prefix' => 'system', 'middleware' => ['role:super-administrator']], function () {
            // System General Setting routes
            Route::get('general-settings', 'Admin\SystemSettingController@general')->name('system.general.settings');
            Route::post('general-settings', 'Admin\SystemSettingController@generalUpdate')->name('system.general.settings.post');
            // System Member meta-data Setting routes
            Route::get('member-meta-settings', 'Admin\SystemSettingController@memberMeta')->name('system.member-meta.settings');
            Route::post('member-meta-settings', 'Admin\SystemSettingController@memberMetaUpdate')->name('system.member-meta.settings.post');
            // System Bonus Setting routes
            Route::get('bonus-settings', 'Admin\SystemSettingController@bonus')->name('system.bonus.settings');
            Route::post('bonus-settings', 'Admin\SystemSettingController@bonusUpdate')->name('system.bonus.settings.post');
            // System Cache Clear routes
            Route::get('cache-clear', 'Admin\SystemSettingController@cacheClear')->name('system.cache.clear');
            Route::post('cache-clear/{cache}', 'Admin\SystemSettingController@cacheClearPost')->name('system.cache.clear.post');
            Route::resources([
                'system-bank' => 'Admin\MasterBankController',
            ]);

app/Models/BonusSetting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BonusSetting extends Model
{
	protected $guarded = [];

    protected $dates = ['active_at', 'created_at', 'updated_at'];

    public function bonuslevel() {
    	return $this->hasMany(BonusLevelSetting::class);
    }

    public function plan() {
    	return $this->belongsTo(Plan::class);
    }
}

resources/views/admin/bonus-setting/create.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="{{ asset('admin/lib/select2/css/select2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/lib/jquery-toggles/toggles-full.css') }}" rel="stylesheet">
    <style>
        .show {
            display: block !important;
        }
        .hidden {
            display: none !important;
            visibility: hidden !important;
        }
        .invisible {
            visibility: hidden;
        }    </style>
@endsection

@section('content')
    <div class="br-pageheader pd-y-15 pd-l-20">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <a class="breadcrumb-item" href="{{ route('home') }}">myflur</a>
            <a class="breadcrumb-item" href="#">admin</a>
            <a class="breadcrumb-item" href="#">settings</a>
            <a class="breadcrumb-item" href="{{ route('bonus-settings.index') }}">bonus setting</a>
            <span class="breadcrumb-item active">tambah bonus baru</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
        <div class="pull-left">
            <h4 class="tx-gray-800 mg-b-5">BONUS SETTINGS</h4>
            <p class="mg-b-0">Tambah Bonus Baru</p>
        </div>
    </div>

    <div class="br-pagebody mg-t-70">
        <div class="br-section-wrapper pd-20">
            <form method="post" action="{{ route('bonus-settings.store') }}" data-parsley-validate>
                @csrf
                <div class="form-layout form-layout-2">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-control-label"><h6>Plan: <span class="tx-danger">*</span></h6></label>
                                <select id="plan_id" name="plan_id" class="form-control select2-show-search" data-placeholder="--- Pilih PLAN ---">
                                    <option label="--- Pilih PLAN ---"></option>
                                    @foreach($plans as $key => $plan)
                                        @if(old('plan_id')==$key)
                                            <option value="{{ $key }}" selected>{{ $plan }}</option>
                                        @else
                                            <option value="{{ $key }}">{{ $plan }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @if($errors->has('plan_id'))
                                    <ul class="parsley-errors-list filled">
                                        <li class="parsley-required">{{ $errors->first('plan_id') }}</li>
                                    </ul>
                                @endif
                            </div>
                        </div><!-- col-4 -->
                        <div class="col-md-8">
                            <div class="form-group mg-l--1">
                                <label class="form-control-label"><h6>Tanggal Aktif: <span class="tx-danger">*</span></h6></label>
                                <input class="form-control parsley-error fc-datepicker" type="text" id="active_at" name="active_at" value="{{ old('active_at') }}" placeholder="Input Tanggal Aktif">
                                @if($errors->has('active_at'))
                                    <ul class="parsley-errors-list filled">
                                        <li class="parsley-required">{{ $errors->first('active_at') }}</li>
                                    </ul>
                                @endif
                            </div>
                        </div>
                    </div><!-- row -->

                    @include('admin.bonus-setting.partials.bonus-nominal')

                    @include('admin.bonus-setting.partials.bonus-pairing')

                    @include('admin.bonus-setting.partials.bonus-pairing-level')

                    @include('admin.bonus-setting.partials.bonus-level')

                    <div class="form-layout-footer bd pd-20 bd-t-0">
                        <button type="submit" class="btn btn-info">Save</button>
                        <a class="btn btn-secondary" href="{{ route('plan-settings.index') }}">Cancel</a>
                        <button type="button" class="btn btn-outline-primary btn-icon rounded-circle tx-34-force pd-0-force bd-0 pull-right"
                                data-container="body"
                                data-toggle="popover"
                                data-popover-color="default"
                                data-placement="top"
                                data-html="true"
                                title="Help"
                                data-content="Under Construction"><div><i class="fa fa-question-circle-o"></i></div></button>
                    </div><!-- form-group -->
                </div><!-- form-layout -->
            </form>
        </div><!-- section-wrapper -->
    </div><!-- br-pagebody -->
@endsection

@section('scripts')
    <script src="{{ asset('admin/lib/select2/js/select2.min.js') }}"></script>
    <script src="{{ asset('admin/lib/jquery-toggles/toggles.min.js') }}"></script>
@endsection

@section('page_script')
    <script>
        $(function(){
            'use strict'

            $('.fc-datepicker').datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                dateFormat: "yy-mm-dd"
            });

            @system('bonus_level')
                @for($i = 1; $i <= 10; $i++)
                    @if(old('bonus_level_amount_'. $i) || $errors->has('bonus_level_amount_'. $i))
                        $('#level-{{ $i }}').removeClass('hidden');
                        $('#bonus_level_amount_{{ $i }}').prop('disabled', false);
                    @endif
                @endfor

                $('#max_level_bonus_level').on('keyup', function() {
                    if ($(this).val() > 10) $(this).val(10);

                    var i = 1;

                    for (i = 1; i <= 10; i++) {
                        $('#bonus_level_amount_'+ i).prop('disabled', true);
                        $('#level-'+ i).addClass('hidden');
                    }

                    for (i = 1; i <= $(this).val(); i++) {
                        $('#level-'+ i).removeClass('hidden');
                        $('#bonus_level_amount_'+ i).prop('disabled', false);
                    }
                });
            @endsystem

            $('.form-layout .form-control').on('focusin', function(){
                $(this).closest('.form-group').addClass('form-group-active');
            });

            $('.form-layout .form-control').on('focusout', function(){
                $(this).closest('.form-group').removeClass('form-group-active');
            });

            $('.select2').on('select2:opening', function (e) {
                $(this).closest('.form-group').addClass('form-group-active');
            });

            $('.select2').on('select2:closing', function (e) {
                $(this).closest('.form-group').removeClass('form-group-active');
            });

        });
    </script>
@endsection

resources/views/admin/bonus-setting/edit.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="{{ asset('admin/lib/select2/css/select2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/lib/jquery-toggles/toggles-full.css') }}" rel="stylesheet">
    <style>
        .show {
            display: block !important;
        }
        .hidden {
            display: none !important;
            visibility: hidden !important;
        }
        .invisible {
            visibility: hidden;
        }    </style>
@endsection

@section('content')
    <div class="br-pageheader pd-y-15 pd-l-20">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <a class="breadcrumb-item" href="{{ route('home') }}">myflur</a>
            <a class="breadcrumb-item" href="#">admin</a>
            <a class="breadcrumb-item" href="#">settings</a>
            <a class="breadcrumb-item" href="{{ route('bonus-settings.index') }}">bonus setting</a>
            <span class="breadcrumb-item active">edit bonus setting</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
        <div class="pull-left">
            <h4 class="tx-gray-800 mg-b-5">BONUS SETTINGS</h4>
            <p class="mg-b-0">Edit Bonus Setting</p>
        </div>
    </div>

    <div class="br-pagebody mg-t-70">
        <div class="br-section-wrapper pd-20">
            <form method="post" action="{{ route('bonus-settings.update',['bonus_setting' => $bonus_setting]) }}" data-parsley-validate>
                @csrf
                <input type="hidden" name="_method" value="PUT">
                <div class="form-layout form-layout-2">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-control-label"><h6>Plan: <span class="tx-danger">*</span></h6></label>
                                <select id="plan_id" name="plan_id" class="form-control select2-show-search" data-placeholder="--- Pilih PLAN ---">
                                    <option label="--- Pilih PLAN ---"></option>
                                    @foreach($plans as $key => $plan)
                                        @if(old('plan_id')==$key || $bonus_setting->plan_id==$key)
                                            <option value="{{ $key }}" selected>{{ $plan }}</option>
                                        @else
                                            <option value="{{ $key }}">{{ $plan }}</option>
                                        @endif
                                    @endforeach
                                </select>
                                @if($errors->has('plan_id'))
                                    <ul class="parsley-errors-list filled">
                                        <li class="parsley-required">{{ $errors->first('plan_id') }}</li>
                                    </ul>
                                @endif
                            </div>
                        </div><!-- col-4 -->
                        <div class="col-md-8">
                            <div class="form-group mg-l--1">
                                <label class="form-control-label"><h6>Tanggal Aktif: <span class="tx-danger">*</span></h6></label>
                                <input class="form-control parsley-error fc-datepicker" type="text" id="active_at" name="active_at" value="{{ $bonus_setting->active_at ? to_utz($bonus_setting->active_at,'Y-m-d') : old('active_at') }}" placeholder="Input Tanggal Aktif">
                                @if($errors->has('active_at'))
                                    <ul class="parsley-errors-list filled">
                                        <li class="parsley-required">{{ $errors->first('active_at') }}</li>
                                    </ul>
                                @endif
                            </div>
                        </div>
                    </div><!-- row -->

                    @include('admin.bonus-setting.partials.bonus-nominal')

                    @include('admin.bonus-setting.partials.bonus-pairing')

                    @include('admin.bonus-setting.partials.bonus-pairing-level')

                    @include('admin.bonus-setting.partials.bonus-level')

                    <div class="form-layout-footer bd pd-20 bd-t-0">
                        <button type="submit" class="btn btn-info">Save</button>
                        <a class="btn btn-secondary" href="{{ route('bonus-settings.index') }}">Cancel</a>
                        <button type="button" class="btn btn-outline-primary btn-icon rounded-circle tx-34-force pd-0-force bd-0 pull-right"
                                data-container="body"
                                data-toggle="popover"
                                data-popover-color="default"
                                data-placement="top"
                                data-html="true"
                                title="Help"
                                data-content="Under Construction"><div><i class="fa fa-question-circle-o"></i></div></button>
                    </div><!-- form-group -->
                </div><!-- form-layout -->
            </form>
        </div><!-- section-wrapper -->
    </div><!-- br-pagebody -->
@endsection

@section('scripts')
    <script src="{{ asset('admin/lib/select2/js/select2.min.js') }}"></script>
    <script src="{{ asset('admin/lib/jquery-toggles/toggles.min.js') }}"></script>
@endsection

@section('page_script')
    <script>
        $(function(){
            'use strict'

            $('.fc-datepicker').datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                dateFormat: "yy-mm-dd"
            });

            @system('bonus_level')
                @for($i = 1; $i <= 10; $i++)
                @if(old('bonus_level_amount_'. $i) || $errors->has('bonus_level_amount_'. $i))
                $('#level-{{ $i }}').removeClass('hidden');
                $('#bonus_level_amount_{{ $i }}').prop('disabled', false);
                @endif
                @endfor

                $('#max_level_bonus_level').on('keyup', function() {
                    if ($(this).val() > 10) $(this).val(10);

                    var i = 1;

                    for (i = 1; i <= 10; i++) {
                        $('#bonus_level_amount_'+ i).prop('disabled', true);
                        $('#level-'+ i).addClass('hidden');
                    }

                    for (i = 1; i <= $(this).val(); i++) {
                        $('#level-'+ i).removeClass('hidden');
                        $('#bonus_level_amount_'+ i).prop('disabled', false);
                    }
                });
            @endsystem

            $('.form-layout .form-control').on('focusin', function(){
                $(this).closest('.form-group').addClass('form-group-active');
            });

            $('.form-layout .form-control').on('focusout', function(){
                $(this).closest('.form-group').removeClass('form-group-active');
            });

            $('.select2').on('select2:opening', function (e) {
                $(this).closest('.form-group').addClass('form-group-active');
            });

            $('.select2').on('select2:closing', function (e) {
                $(this).closest('.form-group').removeClass('form-group-active');
            });

        });
    </script>
@endsection

resources/views/admin/bonus-setting/show.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="{{ asset('admin/lib/select2/css/select2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('admin/lib/jquery-toggles/toggles-full.css') }}" rel="stylesheet">
    <style>
        .show {
            display: block !important;
        }
        .hidden {
            display: none !important;
            visibility: hidden !important;
        }
        .invisible {
            visibility: hidden;
        }    </style>
@endsection

@section('content')
    <div class="br-pageheader pd-y-15 pd-l-20">
        <nav class="breadcrumb pd-0 mg-0 tx-12">
            <a class="breadcrumb-item" href="{{ route('home') }}">myflur</a>
            <a class="breadcrumb-item" href="#">admin</a>
            <a class="breadcrumb-item" href="#">settings</a>
            <a class="breadcrumb-item" href="{{ route('bonus-settings.index') }}">bonus setting</a>
            <span class="breadcrumb-item active">view bonus setting</span>
        </nav>
    </div><!-- br-pageheader -->
    <div class="pd-x-20 pd-sm-x-30 pd-t-20 pd-sm-t-30">
        <div class="pull-left">
            <h4 class="tx-gray-800 mg-b-5">BONUS SETTINGS</h4>
            <p class="mg-b-0">View Bonus Setting</p>
        </div>
    </div>

    <div class="br-pagebody mg-t-70">
        <div class="br-section-wrapper pd-20">
            <div class="form-layout form-layout-2">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="form-control-label"><h6>Plan:</h6></label>
                            <div class="tx-bold tx-black">{{ $bonus_setting->plan->code }} - {{ $bonus_setting->plan->name }}</div>
                        </div>
                    </div><!-- col-4 -->
                    <div class="col-md-8">
                        <div class="form-group mg-l--1">
                            <label class="form-control-label"><h6>Tanggal Aktif:</h6></label>
                            <div class="tx-bold tx-black">{{ to_utz($bonus_setting->active_at) }}</div>
                        </div>
                    </div>
                </div><!-- row -->

                @include('admin.bonus-setting.partials.bonus-nominal-show')

                @include('admin.bonus-setting.partials.bonus-pairing-show')

                @include('admin.bonus-setting.partials.bonus-pairing-level-show')

                @include('admin.bonus-setting.partials.bonus-level-show')

                <div class="form-layout-footer bd pd-20 bd-t-0">
                    <a class="btn btn-secondary" href="{{ route('bonus-settings.index') }}">Back</a>
                </div><!-- form-group -->
            </div><!-- form-layout -->
        </div><!-- section-wrapper -->
    </div><!-- br-pagebody -->
@endsection

@section('scripts')
    <script src="{{ asset('admin/lib/select2/js/select2.min.js') }}"></script>
    <script src="{{ asset('admin/lib/jquery-toggles/toggles.min.js') }}"></script>
@endsection

@section('page_script')
@endsection